name: Release Trigger Check

on:
  release:
    types: [released]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-project-forked-actions-repo:${{ env.RELEASE_VERSION }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: push to dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-project-forked-actions-repo:${{ env.RELEASE_VERSION }}
