name: Release Trigger Check

on:
  release:
    types: [released]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
  
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
  
      - name: Build with Gradle
        run: ./gradlew build 

      - name: build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-project-forked-actions-repo:${{ env.RELEASE_VERSION }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: push to dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-project-forked-actions-repo:${{ env.RELEASE_VERSION }}

      - name: Access other github reo
        uses: actions/checkout@v3
        with:
            repository: LaraibSaleem/workflows-1
            ref: 'main'
            token:  ${{ secrets.PAT_GITHUB }}
  
      - name: setup git config
        run: |
            git config user.name "Laraib Saleem"
            git config user.email "laraibsaleem98@gmail.com"
            yq -i  eval '.images.actionsimagetag= "LaraibSaleem/workflows-1:${{ env.RELEASE_VERSION }}"' testfolder/testfile.yaml
            git add .
            git commit -m "update testfile"
            git push origin main
